
version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  streamlit_ui:
    image: streamlit/streamlit:latest
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    command: streamlit run streamlit_app.py --server.port 8501 --server.headless true
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  simulator:
    build:
      context: ./simulator
    depends_on:
      - backend
