services:
  backend:
    build:
      context: .
    container_name: wgc_backend
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development

  streamlit_ui:
    build:
      context: ./streamlit
    container_name: wgc_streamlit
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  simulator:
    build:
      context: ./simulator
    container_name: wgc_simulator
    depends_on:
      - backend

