name: Keep services alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      # Use Actions secrets if present; otherwise fall back to provided defaults
      SIMULATOR_URL: ${{ secrets.SIMULATOR_URL || 'https://wgc-digitaltwin-bc-3zhl7gknvuadgvnd64z8nr.streamlit.app' }}
      BACKEND_URL:   ${{ secrets.BACKEND_URL   || 'https://wgc-digitaltwin-bc-1.onrender.com' }}
    steps:
      - name: Ping simulator (UI) and backend (API)
        run: |
          set -euo pipefail

          # Normalize
          SIM="${SIMULATOR_URL%%/}"
          BE="${BACKEND_URL%%/}"

          echo "Simulator URL (UI): $SIM"
          echo "Backend URL (API):  $BE"

          # 1) Try the Streamlit UI root (200 if alive)
          echo "Pinging UI (simulator): ${SIM}/"
          curl -fsS "${SIM}/" >/dev/null || echo "UI ping failed (continuing)"

          # 2) Try backend /recent-wgc (expects 200 JSON)
          echo "Pinging backend: ${BE}/recent-wgc"
          curl -fsS "${BE}/recent-wgc" >/dev/null

          echo "Keepalive OK"

